train_settings:
  random_state : 42
  model_export : True
model_parameters:
  name_model: "log_reg_static"
  multi_class_lr: "ovr"
  max_iter_lr: 10000
  selected_features:
    - "sepal length (cm)"
    - "sepal width (cm)"
    - "petal length (cm)"
    - "petal width (cm)"
  target: "target" # y
  grid_search:
    C:
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
      - 1000
    penalty:
    - l2
  # - l1
  # - elasticnet


